@startuml
'https://plantuml.com/class-diagram

'Entity,Viewの仲介、操作する、Entity、View以外に依存しないように
class Logic

'MonoBehaviour
class View

'Unityに依存しないデータ
class Entity

Entity <|-- Logic
View <|-- Logic
'Logic <|-- GameManager
Logic <|-- Controller
Controller <|-- GameManager
GameManager <|-- Container



@enduml